var util = {};
util = {
    // 步数测试数据
    steps:{
        total: 700,
        list: [

            {
                "ASId": 6,
                "ASStatus": 1,
                "ASIsDel": 0,
                "AS_AMId": 2,
                "ASDeviceId": "",
                "AS_ASUuid": "",
                "AS_ACUuid": "",
                "ASDataType": 7,
                "ASStartTime": "2017-11-09T19:22:00",
                "ASEndTime": "2017-11-16T19:22:00",
                "ASSteps": 5452,
                "ASMileage": 0,
                "ASTheMileage": 2,
                "ASWalkingTime": 0,
                "ASRnningTime": 0,
                "ASCAL": 0,
                "ASRnningCAL": 0,
                "ASAimSteps": 10000,
                "ASCreateDate": "2017-11-09T19:22:00",
                "PkValue": 6
            },
            {
                "ASId": 3,
                "ASStatus": 1,
                "ASIsDel": 0,
                "AS_AMId": 2,
                "ASDeviceId": "",
                "AS_ASUuid": "",
                "AS_ACUuid": "",
                "ASDataType": 1,
                "ASStartTime": "2017-11-12T19:22:00",
                "ASEndTime": "2017-11-18T19:22:00",
                "ASSteps": 40000,
                "ASMileage": 0,
                "ASTheMileage": 50,
                "ASWalkingTime": 30,
                "ASRnningTime": 20,
                "ASCAL": 80,
                "ASRnningCAL": 20,
                "ASAimSteps": 10,
                "ASCreateDate": "2017-11-10T19:22:00",
                "PkValue": 3
            },
            {
                "ASId": 5,
                "ASStatus": 1,
                "ASIsDel": 0,
                "AS_AMId": 2,
                "ASDeviceId": "",
                "AS_ASUuid": "",
                "AS_ACUuid": "",
                "ASDataType": 5,
                "ASStartTime": "2017-11-15T19:22:00",
                "ASEndTime": "2017-11-19T19:22:00",
                "ASSteps": 10000,
                "ASMileage": 0,
                "ASTheMileage": 500,
                "ASWalkingTime": 300,
                "ASRnningTime": 20,
                "ASCAL": 80,
                "ASRnningCAL": 20,
                "ASAimSteps": 10,
                "ASCreateDate": "2017-11-11T19:22:00",
                "PkValue": 5
            },
            {
                "ASId": 7,
                "ASStatus": 1,
                "ASIsDel": 0,
                "AS_AMId": 2,
                "ASDeviceId": "",
                "AS_ASUuid": "",
                "AS_ACUuid": "",
                "ASDataType": 7,
                "ASStartTime": "2017-11-29T19:22:00",
                "ASEndTime": "2017-11-29T19:22:00",
                "ASSteps": 17300,
                "ASMileage": 0,
                "ASTheMileage": 500,
                "ASWalkingTime": 300,
                "ASRnningTime": 20,
                "ASCAL": 80,
                "ASRnningCAL": 20,
                "ASAimSteps": 10,
                "ASCreateDate": "2017-11-22T19:22:00",
                "PkValue": 7
            },
            {
                "ASId": 7,
                "ASStatus": 1,
                "ASIsDel": 0,
                "AS_AMId": 2,
                "ASDeviceId": "",
                "AS_ASUuid": "",
                "AS_ACUuid": "",
                "ASDataType": 7,
                "ASStartTime": "2017-11-29T19:22:00",
                "ASEndTime": "2017-11-25T19:22:00",
                "ASSteps": 2300,
                "ASMileage": 0,
                "ASTheMileage": 500,
                "ASWalkingTime": 300,
                "ASRnningTime": 20,
                "ASCAL": 80,
                "ASRnningCAL": 20,
                "ASAimSteps": 10,
                "ASCreateDate": "2017-11-22T19:22:00",
                "PkValue": 7
            },
            {
                "ASId": 2,
                "ASStatus": 1,
                "ASIsDel": 0,
                "AS_AMId": 2,
                "ASDeviceId": "",
                "AS_ASUuid": "",
                "AS_ACUuid": "",
                "ASDataType": 1,
                "ASStartTime": "2017-11-29T19:22:00",
                "ASEndTime": "2017-11-30T19:22:00",
                "ASSteps": 10500,
                "ASMileage": 0,
                "ASTheMileage": 0,
                "ASWalkingTime": 0,
                "ASRnningTime": 0,
                "ASCAL": 0,
                "ASRnningCAL": 0,
                "ASAimSteps": 0,
                "ASCreateDate": "2017-11-24T19:22:00",
                "PkValue": 2
            },
            {
                "ASId": 4,
                "ASStatus": 1,
                "ASIsDel": 0,
                "AS_AMId": 2,
                "ASDeviceId": "",
                "AS_ASUuid": "",
                "AS_ACUuid": "",
                "ASDataType": 5,
                "ASStartTime": "2017-12-01T19:22:00",
                "ASEndTime": "2017-12-03T19:22:00",
                "ASSteps": 1355,
                "ASMileage": 0,
                "ASTheMileage": 2,
                "ASWalkingTime": 0,
                "ASRnningTime": 0,
                "ASCAL": 0,
                "ASRnningCAL": 0,
                "ASAimSteps": 0,
                "ASCreateDate": "2017-11-25T19:22:00",
                "PkValue": 4
            }
        ],

    },
    

    sleep: {
        total: 700,
        list: [
            {
                "APId": 5,
                "APStatus": 1,
                "APIsDel": 0,
                "AP_AMId": 2,
                "APDeviceId": "",
                "AP_ASUuid": "",
                "AP_ACUuid": "",
                "APDataType": 3,
                "APStartTime": "2017-11-09T00:00:00",
                "APEndTime": "2017-11-15T19:22:00",
                "APSleepTime": 1080,
                "APShallowSleepTime": 530,
                "APDeepSleepTime": 550,
                "APAimSteps": 1080,
                "APCreateDate": "2017-11-22T14:25:00",
                "PkValue": 5,
                "APAimSteps": 400,
            },
            {
                "APId": 6,
                "APStatus": 1,
                "APIsDel": 0,
                "AP_AMId": 2,
                "APDeviceId": "",
                "AP_ASUuid": "",
                "AP_ACUuid": "",
                "APDataType": 5,
                "APStartTime": "2017-11-11T00:00:00",
                "APEndTime": "2017-11-16T19:22:00",
                "APSleepTime": 300,
                "APShallowSleepTime": 120,
                "APDeepSleepTime": 180,
                "APAimSteps": 300,
                "APCreateDate": "2017-11-22T14:25:00",
                "PkValue": 6
            },
            {
                "APId": 6,
                "APStatus": 1,
                "APIsDel": 0,
                "AP_AMId": 2,
                "APDeviceId": "",
                "AP_ASUuid": "",
                "AP_ACUuid": "",
                "APDataType": 5,
                "APStartTime": "2017-11-12T00:00:00",
                "APEndTime": "2017-11-18T19:22:00",
                "APSleepTime": 300,
                "APShallowSleepTime": 120,
                "APDeepSleepTime": 180,
                "APAimSteps": 300,
                "APCreateDate": "2017-11-22T14:25:00",
                "PkValue": 6
            },
            {
                "APId": 6,
                "APStatus": 1,
                "APIsDel": 0,
                "AP_AMId": 2,
                "APDeviceId": "",
                "AP_ASUuid": "",
                "AP_ACUuid": "",
                "APDataType": 5,
                "APStartTime": "2017-11-20T00:00:00",
                "APEndTime": "2017-11-21T19:22:00",
                "APSleepTime": 420,
                "APShallowSleepTime": 120,
                "APDeepSleepTime": 300,
                "APAimSteps": 420,
                "APCreateDate": "2017-11-22T14:25:00",
                "PkValue": 6
            },
            {
                "APId": 6,
                "APStatus": 1,
                "APIsDel": 0,
                "AP_AMId": 2,
                "APDeviceId": "",
                "AP_ASUuid": "",
                "AP_ACUuid": "",
                "APDataType": 5,
                "APStartTime": "2017-11-24T00:00:00",
                "APEndTime": "2017-11-24T19:22:00",
                "APSleepTime": 300,
                "APShallowSleepTime": 120,
                "APDeepSleepTime": 180,
                "APAimSteps": 300,
                "APCreateDate": "2017-11-22T14:25:00",
                "PkValue": 6
            },
            {
                "APId": 6,
                "APStatus": 1,
                "APIsDel": 0,
                "AP_AMId": 2,
                "APDeviceId": "",
                "AP_ASUuid": "",
                "AP_ACUuid": "",
                "APDataType": 5,
                "APStartTime": "2017-11-25T00:00:00",
                "APEndTime": "2017-11-27T19:22:00",
                "APSleepTime": 300,
                "APShallowSleepTime": 120,
                "APDeepSleepTime": 180,
                "APAimSteps": 300,
                "APCreateDate": "2017-11-22T14:25:00",
                "PkValue": 6
            },
            {
                "APId": 6,
                "APStatus": 1,
                "APIsDel": 0,
                "AP_AMId": 2,
                "APDeviceId": "",
                "AP_ASUuid": "",
                "AP_ACUuid": "",
                "APDataType": 5,
                "APStartTime": "2017-11-09T00:00:00",
                "APEndTime": "2017-11-22T19:22:00",
                "APSleepTime": 720,
                "APShallowSleepTime": 370,
                "APDeepSleepTime": 350,
                "APAimSteps": 720,
                "APCreateDate": "2017-11-22T14:25:00",
                "PkValue": 6
            }
        ],
        list2: [
            {
                "APId": 5,
                "APStatus": 1,
                "APIsDel": 0,
                "AP_AMId": 2,
                "APDeviceId": "",
                "AP_ASUuid": "",
                "AP_ACUuid": "",
                "APDataType": 3,
                "APStartTime": "2017-11-09T00:00:00",
                "APEndTime": "2017-12-15T19:22:00",
                "APSleepTime": 1080,
                "APShallowSleepTime": 530,
                "APDeepSleepTime": 550,
                "APAimSteps": 1080,
                "APCreateDate": "2017-11-22T14:25:00",
                "PkValue": 5,
                "APAimSteps": 400,
            },
            {
                "APId": 6,
                "APStatus": 1,
                "APIsDel": 0,
                "AP_AMId": 2,
                "APDeviceId": "",
                "AP_ASUuid": "",
                "AP_ACUuid": "",
                "APDataType": 5,
                "APStartTime": "2017-11-11T00:00:00",
                "APEndTime": "2017-12-16T19:22:00",
                "APSleepTime": 300,
                "APShallowSleepTime": 120,
                "APDeepSleepTime": 180,
                "APAimSteps": 300,
                "APCreateDate": "2017-11-22T14:25:00",
                "PkValue": 6
            },
            {
                "APId": 6,
                "APStatus": 1,
                "APIsDel": 0,
                "AP_AMId": 2,
                "APDeviceId": "",
                "AP_ASUuid": "",
                "AP_ACUuid": "",
                "APDataType": 5,
                "APStartTime": "2017-11-11T00:00:00",
                "APEndTime": "2017-12-17T19:22:00",
                "APSleepTime": 300,
                "APShallowSleepTime": 120,
                "APDeepSleepTime": 180,
                "APAimSteps": 300,
                "APCreateDate": "2017-11-22T14:25:00",
                "PkValue": 6
            }
            
        ]
    },
    blue: {
        "DeviceCode": "B3",
        "DeviceType": "1",
        "DeviceName": "健康手环",
        "DeviceImg": "",
        "DeviceSign": "",
        "AppServers": [
            {
                "ServerUuid": "6E400001-B5A3-F393-E0A9-E50E24DCCA9E",
                "ServerName": "服务1",
                "isPrimary": false,
                "AppCharacteristics": [
                    {
                        "ACUuid": "6E400003-B5A3-F393-E0A9-E50E24DCCA9E",
                        "ACName": "allread",
                        "Properties": "read"
                    },
                    {
                        "ACUuid": "6E400002-B5A3-F393-E0A9-E50E24DCCA9E",
                        "ACName": "write",
                        "Properties": "read"
                    }
                ]
            }
        ]
    }

};
module.exports = util;